source/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accounts.views import RegisterView, ProfileView, UserChangeView, UserPasswordChangeView

app_name = 'accounts'
urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='registration'),
    path('<int:pk>/profile/', ProfileView.as_view(), name='profile'),
    path('<int:pk>/profile/change/', UserChangeView.as_view(), name='change-profile'),
    path('<int:pk>/profile/change-password/', UserPasswordChangeView.as_view(), name='change-password'),

]

source/hello/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/accounts/models.py
from django.db import models
from django.contrib.auth import get_user_model


def user_directory_path(instance, filename):
    return 'user_{0}/avatars/{1}'.format(instance.user.id, filename)


class Profile(models.Model):
    user = models.OneToOneField(get_user_model(), related_name='profile', on_delete=models.CASCADE,
                                verbose_name='Пользователь')
    birth_date = models.DateField(null=True, blank=True, verbose_name='Дата рождения')
    avatar = models.ImageField(null=True, blank=True, upload_to=user_directory_path, verbose_name='Аватар')

    def __str__(self):
        return self.user.get_full_name() + "'s Profile"

    class Meta:
        db_table = 'profiles'
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'

source/accounts/forms/user_creation_form.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.forms import ModelForm

from accounts.models import Profile

User = get_user_model()


class MyUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = ['username', 'password1', 'password2', 'first_name', 'last_name', 'email']


class UserChangeForm(ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']
        labels = {'first_name': 'Имя', 'last_name': 'Фамилия', 'email': 'Email'}


class ProfileChangeForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['birth_date', 'avatar']

source/accounts/views.py
from django.contrib.auth import get_user_model, login
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.views import PasswordChangeView
from django.core.paginator import Paginator
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse
from django.views.generic import CreateView, DetailView, UpdateView
from accounts.forms import MyUserCreationForm
from accounts.forms.user_creation_form import UserChangeForm, ProfileChangeForm
from accounts.models import Profile

User = get_user_model()


class RegisterView(CreateView):
    template_name = "user_create.html"
    model = User
    form_class = MyUserCreationForm

    def form_valid(self, form):
        user = form.save()
        Profile.objects.create(user=user)
        login(self.request, user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        next = self.request.GET.get('next')
        if not next:
            next = self.request.POST.get('next')
        if not next:
            next = reverse("webapp:index")
        return next


class ProfileView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'user_profile.html'
    context_object_name = 'user_obj'
    paginate_related_by = 12

    def get_context_data(self, **kwargs):
        articles = self.object.articles.order_by('-created_at')
        paginator = Paginator(articles, self.paginate_related_by)
        page_number = self.request.GET.get('page', 1)
        page = paginator.get_page(page_number)
        kwargs['page_obj'] = page
        kwargs['articles'] = page.object_list
        kwargs['is_paginated'] = page.has_other_pages()
        return super().get_context_data(**kwargs)


class UserChangeView(PermissionRequiredMixin, UpdateView):
    model = User
    form_class = UserChangeForm
    template_name = 'user_change.html'
    context_object_name = 'user_obj'

    def has_permission(self):
        return self.get_object() == self.request.user

    def get_context_data(self, **kwargs):
        if 'profile_form' not in kwargs:
            kwargs['profile_form'] = self.get_profile_form()
        return super().get_context_data(**kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        profile_form = self.get_profile_form()
        if form.is_valid() and profile_form.is_valid():
            return self.form_valid(form, profile_form)
        else:
            return self.form_invalid(form, profile_form)

    def form_valid(self, form, profile_form):
        response = super().form_valid(form)
        profile_form.save()
        return response

    def form_invalid(self, form, profile_form):
        context = self.get_context_data(form=form, profile_form=profile_form)
        return self.render_to_response(context)

    def get_profile_form(self):
        form_kwargs = {'instance': self.object.profile}
        if self.request.method == 'POST':
            form_kwargs['data'] = self.request.POST
            form_kwargs['files'] = self.request.FILES
        return ProfileChangeForm(**form_kwargs)

    def get_success_url(self):
        return reverse('accounts:profile', kwargs={'pk': self.object.pk})



class UserPasswordChangeView(PermissionRequiredMixin, PasswordChangeView):
    template_name = 'user_password_change.html'

    def get_success_url(self):
        return reverse('accounts:profile', kwargs={'pk': self.request.user.pk})

    def has_permission(self):
        user = get_object_or_404(User, pk=self.kwargs['pk'])
        return user == self.request.user

source/accounts/templates/login.html
{% extends 'base.html' %}

{% block content %}
    {{ next }}
    <h1>Вход</h1>
    <form action="" method="post" class="text-center">
    {% include 'partial/form.html' with button_text="Войти" %}
    </form>
{% endblock %}

source/accounts/templates/user_change.html
{% extends 'base.html' %}


{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
        {% include 'partial/form.html' %}
        {% include 'partial/form.html' with form=profile_form button_text="Редактировать"%}
    </form>
{% endblock %}

source/accounts/templates/user_create.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post">
        {% include 'partial/form.html' with button_text='Зарегистрироваться' %}
    </form>
{% endblock %}

source/accounts/templates/user_password_change.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post">
        {% include 'partial/form.html' with button_text='Сменить пароль' %}
    </form>
{% endblock %}

source/accounts/templates/user_profile.html
{% extends 'base.html' %}



{% block nav %}
    {% if user == user_obj %}
        <li class="nav-item">
            <a class="nav-link active" aria-current="page"
               href="{% url 'accounts:change-profile' user_obj.pk %}">Change profile</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" aria-current="page"
               href="{% url 'accounts:change-password' user_obj.pk %}">Change password</a>
        </li>
    {% endif %}
{% endblock %}

{% block content %}
    <div class="card" style="width: 18rem;">
        {% if  user_obj.profile.avatar %}
            <img src="{{ user_obj.profile.avatar.url }}" class="card-img-top" alt="...">
        {% endif %}
        <div class="card-body">
            <h5 class="card-title">Username - {{ user_obj.username }}</h5>
            <p>Email - {{ user_obj.email }}</p>
            <p class="card-text">Birthday - {{ user_obj.profile.birth_date|default:"не указан" }}</p>
        </div>
    </div>
    {% include "partial/articles_list.html" %}
{% endblock %}