source/hello/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path

from webapp.views import UpdateArticleView, DeleteArticleView, ArticleListView, CreateArticleView, DetailArticleView, like_views
from webapp.views.comments import CreateCommentView, UpdateCommentView, DeleteCommentView

app_name = 'webapp'

#webapp:index
urlpatterns = [
    path('', ArticleListView.as_view(), name='index'),
    path('add-article/', CreateArticleView.as_view(), name='add-article'),
    path('article/<int:pk>/', DetailArticleView.as_view(), name='article-detail'),
    path('article/<int:pk>/update/', UpdateArticleView.as_view(), name='article-update'),
    path('article/<int:pk>/delete/', DeleteArticleView.as_view(), name='article-delete'),

    path('article/<int:pk>/add-comment/', CreateCommentView.as_view(), name='add-comment'),
    path('comment/<int:pk>/update/', UpdateCommentView.as_view(), name='comment-update'),
    path('comment/<int:pk>/delete/', DeleteCommentView.as_view(), name='comment-delete'),
    path('article/<int:article_id>/like/', like_views.toggle_article_like, name='article_like'),
    path('comment/<int:comment_id>/like/', like_views.toggle_comment_like, name='comment_like'),
]

source/webapp/models/article.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

from webapp.models.base_create_update import BaseCreateUpdateModel

statuses = [("new", "Новая"), ("moderated", "Модерированная"), ("deleted", "Удаленные")]


class Article(BaseCreateUpdateModel):
    title = models.CharField(max_length=50, verbose_name='Название', null=False, blank=False)
    content = models.TextField(verbose_name='Контент')
    author = models.ForeignKey(get_user_model(), related_name='articles', on_delete=models.SET_DEFAULT, default=1, verbose_name="Автор")
    status = models.CharField(max_length=20, verbose_name="Статус", choices=statuses, default=statuses[0][0])
    tags = models.ManyToManyField(
        "webapp.Tag",
        verbose_name='Теги',
        related_name='articles',
        blank=True,
        through='webapp.ArticleTag',
        through_fields=("article", "tag"),
    )

    def __str__(self):
        return f"{self.id} - {self.title}"

    class Meta:
        db_table = 'articles'
        verbose_name = 'Статья'
        verbose_name_plural = "Статьи"
        permissions = [("change_article_status", "Can change article status")]


    def get_absolute_url(self):
        return reverse('webapp:article-detail', kwargs={'pk': self.pk})

source/webapp/models/article_tag.py
from django.db import models

from webapp.models.base_create_update import BaseCreateUpdateModel


class ArticleTag(BaseCreateUpdateModel):
    article = models.ForeignKey('webapp.Article', related_name='articles_tags', on_delete=models.CASCADE,)
    tag = models.ForeignKey('webapp.Tag', related_name='tags_articles', on_delete=models.CASCADE,)

source/webapp/models/base_create_update.py
from django.db import models


class BaseCreateUpdateModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')

    class Meta:
        abstract = True

source/webapp/models/comment.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

from webapp.models.base_create_update import BaseCreateUpdateModel


class Comment(BaseCreateUpdateModel):
    article = models.ForeignKey(
        'webapp.Article',
        related_name='comments',
        on_delete=models.CASCADE,
        verbose_name='Статья'
    )
    text = models.TextField(max_length=400, verbose_name='Комментарий')
    author = models.ForeignKey(
        get_user_model(),
        related_name='comments',
        on_delete=models.SET_DEFAULT,
        default=1,
        verbose_name="Автор"
    )
    likes = models.ManyToManyField(
        get_user_model(),
        through='webapp.CommentLike',
        related_name='liked_comments',
        blank=True,
        verbose_name='Лайки'
    )

    def __str__(self):
        return self.text[:20]

    class Meta:
        db_table = 'comments'
        verbose_name = 'Комментарий'
        verbose_name_plural = "Комментарии"

    def get_absolute_url(self):
        return reverse("webapp:article-detail", kwargs={"pk": self.article_id})

source/webapp/models/like.py
from django.conf import settings
from django.db import models
from webapp.models.article import Article
from webapp.models.comment import Comment

class ArticleLike(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='likes')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('article', 'user')


class CommentLike(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='comment_likes')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('comment', 'user')

source/webapp/models/tag.py
from django.db import models

from webapp.models.base_create_update import BaseCreateUpdateModel


class Tag(BaseCreateUpdateModel):
    title = models.CharField(max_length=50, verbose_name='Название', null=False, blank=False, unique=True)

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'tags'
        verbose_name = 'Тэг'
        verbose_name_plural = "Тэги"

source/webapp/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import widgets

from webapp.models import Article


class ArticleForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for v in self.visible_fields():
            if not isinstance(v.field.widget, widgets.CheckboxSelectMultiple):
                v.field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Article
        fields = ('title', 'author', 'content', 'status', 'tags',)
        widgets = {
            'tags': forms.CheckboxSelectMultiple(),
        }

    def clean_title(self):
        title = self.cleaned_data['title']
        if len(title) < 5:
            raise ValidationError("Title must be at least 5 characters long")
        return title

    def clean(self):
        title = self.cleaned_data.get('title')
        content = self.cleaned_data.get('content')
        if title and content and title == content:
            raise ValidationError("Название и контент не могут быть одинаковыми")
        return self.cleaned_data

source/webapp/forms/articles.py
from django import forms
from django.core.exceptions import ValidationError
from webapp.forms.base_form import BaseForm
from webapp.models import Article


class ArticleForm(BaseForm):

    class Meta:
        model = Article
        fields = ('title', 'content', 'status', 'tags',)
        widgets = {
            'tags': forms.CheckboxSelectMultiple(),
        }

    def clean_title(self):
        title = self.cleaned_data['title']
        if len(title) < 5:
            raise ValidationError("Title must be at least 5 characters long")
        return title

    def clean(self):
        title = self.cleaned_data.get('title')
        content = self.cleaned_data.get('content')
        if title and content and title == content:
            raise ValidationError("Название и контент не могут быть одинаковыми")
        return self.cleaned_data

source/webapp/forms/base_form.py
from django import forms
from django.forms import widgets


class BaseForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for v in self.visible_fields():
            if not isinstance(v.field.widget, widgets.CheckboxSelectMultiple):
                v.field.widget.attrs['class'] = 'form-control'

source/webapp/forms/comments.py
from django import forms

from webapp.forms.base_form import BaseForm
from webapp.models import Comment


class CommentForm(BaseForm):

    class Meta:
        model = Comment
        fields = ('text',)

source/webapp/forms/search.py
from django import forms



class SearchForm(forms.Form):
    search = forms.CharField(label='Найти', max_length=100, required=False)

source/webapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic import TemplateView, FormView

from webapp.forms import ArticleForm

from webapp.models import Article


class IndexView(View):

    def get(self, request):
        articles = Article.objects.order_by('-created_at')
        return render(request, 'index.html', {"articles": articles})


class CreateView(FormView):
    template_name = 'create_article.html'
    form_class = ArticleForm

    def form_valid(self, form):
        article = form.save()
        return redirect("article-detail", pk=article.pk)


class UpdateView(FormView):
    template_name = 'update_article.html'
    form_class = ArticleForm

    def dispatch(self, request, *args, **kwargs):
        self.article = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def get_object(self):
        return get_object_or_404(Article, pk=self.kwargs['pk'])

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['instance'] = self.article
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['article'] = self.article
        return context

    def form_valid(self, form):
        form.save()
        return redirect("article-detail", pk=self.article.pk)


def delete_article(request, *args, pk, **kwargs):
    article = get_object_or_404(Article, pk=pk)
    if request.method == "POST":
        article.delete()
        return redirect("index")
    else:
        return render(request, 'delete_article.html', {"article": article})


class DetailView(TemplateView):
    template_name = 'detail_article.html'

    def dispatch(self, request, *args, **kwargs):
        self.article = get_object_or_404(Article, pk=self.kwargs['pk'])
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['article'] = self.article
        return context

    # def get_template_names(self):
    #     if self.article.status == "deleted":
    #         return ["deleted_article.html"]
    #     else:
    #         return ['detail_article.html']

source/webapp/views/articles.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.http import urlencode
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from webapp.models.like import CommentLike
from webapp.forms import ArticleForm, SearchForm
from webapp.models import Article


class ArticleListView(ListView):
    template_name = 'articles/index.html'
    model = Article
    context_object_name = "articles"
    ordering = ['-created_at']
    paginate_by = 12

    def dispatch(self, request, *args, **kwargs):
        print(request.user)
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            queryset = queryset.filter(
                Q(title__icontains=self.search_value) |
                Q(author__icontains=self.search_value)
            )

        if self.request.user.is_authenticated:
            for article in queryset:
                article.is_liked_by_user = article.likes.filter(user=self.request.user).exists()

        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        result = super().get_context_data(**kwargs)
        result['search_form'] = self.form
        if self.search_value:
            result["query"] = urlencode({"search": self.search_value})
            result['search'] = self.search_value
        return result

    def get_search_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None

class CreateArticleView(LoginRequiredMixin, CreateView):
    template_name = 'articles/create_article.html'
    # model = Article
    # fields = ['title', 'author', 'content', 'tags']
    form_class = ArticleForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class UpdateArticleView(PermissionRequiredMixin ,UpdateView):
    template_name = 'articles/update_article.html'
    form_class = ArticleForm
    model = Article

    permission_required = 'webapp.change_article'

    def has_permission(self):
        return super().has_permission() or self.request.user == self.get_object().author

    # def dispatch(self, request, *args, **kwargs):
    #     user = request.user
    #     if not user.is_authenticated:
    #         return redirect('webapp:index')
    #     if not user.has_perm('webapp.change_article'):
    #         raise PermissionDenied
    #     return super().dispatch(request, *args, **kwargs)


class DeleteArticleView(PermissionRequiredMixin, DeleteView):
    model = Article
    template_name = 'articles/delete_article.html'
    success_url = reverse_lazy('webapp:index')

    permission_required = "webapp.delete_article"

    def has_permission(self):
        return super().has_permission() or self.request.user == self.get_object().author

class DetailArticleView(DetailView):
    template_name = 'articles/detail_article.html'
    model = Article

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        comments = self.object.comments.order_by('-created_at')

        if self.request.user.is_authenticated:
            for comment in comments:
                comment.is_liked_by_user = CommentLike.objects.filter(
                    comment=comment,
                    user=self.request.user
                ).exists()
                comment.likes_count = CommentLike.objects.filter(comment=comment).count()

        context['comments'] = comments
        return context

source/webapp/views/comments.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.views.generic import CreateView, UpdateView, DeleteView

from webapp.forms.comments import CommentForm
from webapp.models import Article, Comment


class CreateCommentView(LoginRequiredMixin, CreateView):
    form_class = CommentForm
    template_name = "comments/create_comment.html"


    def form_valid(self, form):
        article = get_object_or_404(Article, pk=self.kwargs['pk'])
        form.instance.article = article
        form.instance.author = self.request.user
        return super().form_valid(form)



class UpdateCommentView(UpdateView):
    model = Comment
    form_class = CommentForm
    template_name = "comments/update_comment.html"



class DeleteCommentView(DeleteView):
    model = Comment

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        return self.delete(request, *args, **kwargs)


    def get_success_url(self):
        return self.object.get_absolute_url()

source/webapp/views/like_views.py
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404

from webapp.models.article import Article
from webapp.models.comment import Comment
from webapp.models.like import ArticleLike, CommentLike


@login_required
def toggle_article_like(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    like, created = ArticleLike.objects.get_or_create(article=article, user=request.user)

    if not created:
        like.delete()
        liked = False
    else:
        liked = True

    likes_count = article.likes.count()

    return JsonResponse({'likes_count': likes_count, 'liked': liked})


@login_required
def toggle_comment_like(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    like, created = CommentLike.objects.get_or_create(comment=comment, user=request.user)

    if not created:
        like.delete()
        liked = False
    else:
        liked = True

    likes_count = comment.likes.count()

    return JsonResponse({'likes_count': likes_count, 'liked': liked})

source/webapp/templates/partial/article_form.html
{% csrf_token %}


{% for error in form.non_field_errors %}
   <p class="text-danger">{{ error }}</p>
{% endfor %}

{% for field in form %}
   <p><label for="{{ field.id_for_label }}">{{ field.label }}</label></p>
   {% for error in field.errors %}
       <p class="text-danger">{{ error }}</p>
   {% endfor %}
   <p>{{ field }}</p>
{% endfor %}

<input type="submit" value="{{ button_text }}"/>

source/webapp/templates/partial/articles_list.html
{% extends 'base.html' %}

{% block title %}
    <title>Articles</title>
{% endblock %}

{% block content %}
<div class="row mt-3">
    {% for article in articles %}
        <div class="col-12 col-md-4 col-lg-3 mb-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">{{ article.title }}</h5>
                    <h6 class="card-subtitle mb-2 text-body-secondary">{{ article.author }}</h6>
                    <a href="{% url 'webapp:article-detail' article.pk %}"
                       class="card-link btn btn-primary">Detail</a>

                    {% if perms.webapp.change_article or user == article.author %}
                        <a href="{% url 'webapp:article-update' article.pk %}"
                           class="card-link btn btn-primary">Update</a>
                    {% endif %}
                    {% if perms.webapp.delete_article or user == article.author %}
                        <a href="{% url 'webapp:article-delete' article.pk %}"
                           class="card-link btn btn-primary">Delete</a>
                    {% endif %}

                    {% if user.is_authenticated %}
                        <div class="mt-2">
                            <button class="like-btn btn btn-outline-primary"
                                    data-id="{{ article.id }}"
                                    data-type="article"
                                    data-liked="{{ article.is_liked_by_user|yesno:'true,false' }}">
                                {% if article.is_liked_by_user %}Анлайк{% else %}Лайк{% endif %}
                            </button>
                            <span class="likes-count">{{ article.likes_count }}</span>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    {% empty %}
        <p>No articles</p>
    {% endfor %}
</div>

{% if is_paginated %}
    {% include "partial/pagination.html" %}
{% endif %}

{% load static %}
<script src="{% static 'js/likes.js' %}"></script>
{% endblock %}

source/webapp/templates/partial/form.html
{% if button_text %}
    {% csrf_token %}
{% endif %}

{% for error in form.non_field_errors %}
    <p class="text-danger">{{ error }}</p>
{% endfor %}

{% for field in form %}
    <p><label for="{{ field.id_for_label }}">{{ field.label }}</label></p>
    {% for error in field.errors %}
        <p class="text-danger">{{ error }}</p>
    {% endfor %}
    <p>{{ field }}</p>
{% endfor %}

{% if button_text %}
    <input type="submit" value="{{ button_text }}"/>
{% endif %}

source/webapp/templates/partial/pagination.html
<div class="pagination">
    <span class="step-links">
        <a href="?page=1{% if query %}&{{ query }}{% endif %}">&laquo; В начало</a>
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}{% if query %}&{{ query }}{% endif %}">Назад</a>
        {% else %}
            <span class="page-disabled">Назад</span>
        {% endif %}

        <form class="current-page" method="get">
            <label for="page">
                Страница <input type="text" name="page" id="page" value="{{ page_obj.number }}">
                из {{ page_obj.paginator.num_pages }}.
                <input type="hidden" name="search" value="{{ search }}">
            </label>
        </form>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}{% if query %}&{{ query }}{% endif %}">Далее</a>
        {% else %}
            <span class="page-disabled">Далее</span>
        {% endif %}
        <a href="?page={{ page_obj.paginator.num_pages }}{% if query %}&{{ query }}{% endif %}">В конец &raquo;</a>
    </span>
</div>

source/webapp/templates/partial/simple_search.html
<form class="text-center" method="GET">
    <label for="{{ form.search.id_for_label }}">{{ form.search.label }}:</label>
    {{ form.search }}
    <input type="submit" value="Поиск">
</form>